### ISSUE TITLE
Robot.java cleanup

### ISSUE THREAD

**Issue by simon-andrews** [Team4761/2017-Robot-Code#59]
* SmartDashboard stuff can be moved to OI (see #57)
* Initialization of hardware components ought to belong in the constructors of the subsystems
* Mid and Max auto don't really exist, so we shouldn't be initializing them
* ~Gyro doesn't exist anymore so we can remove that stuff~ Gyro is coming back
* Probably some other stuff too

**Comment by bshin100** [comment]
🔪
